// flow-typed signature: d9950267de713fdcc3982ad437ef62df
// flow-typed version: <<STUB>>/babel-plugin-object-rest-spread_v^0.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-object-rest-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "babel-plugin-object-rest-spread" {
  declare module.exports: any;
}
