FROM ubuntu:16.04

WORKDIR /build

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y \
  curl \
  git \
  apt-utils \
  sudo \
  apt-transport-https \
  gcc g++ make
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update
RUN apt-get install -y yarn
RUN apt-get install -y build-essential

#install nvm
#RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
#RUN export NVM_DIR="$HOME/.nvm"
#RUN echo $NVM_DIR
#RUN echo $HOME
#RUN  \. "$HOME/.nvm/nvm.sh"  && nvm install 9.10 # This loads nvm
# RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
RUN apt-get install -y nodejs


RUN node --version
RUN yarn --version


# parity 1.9.0
RUN apt-get install -y wget
RUN wget -q https://parity-downloads-mirror.parity.io/v1.9.0/x86_64-unknown-linux-gnu/parity_1.9.0_amd64.deb && dpkg -i parity_1.9.0_amd64.deb

RUN ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime

# paratii-parity
WORKDIR /paratii-parity
#RUN mkdir /paratii-parity/logs
#ADD chain.json .
# ADD parity-config.toml .


# paratii-portal
WORKDIR /paratii-portal
# ADD . /paratii-portal
# RUN yarn install
