FROM centos:latest

WORKDIR /build

RUN yum clean all

RUN yum -y install centos-release-scl
RUN yum -y install epel-release curl wget git gcc gcc-c++ make
RUN yum -y install openssl libssl-devel libudev-devel openssl-devel

# openssl 1.1.0

RUN wget https://www.openssl.org/source/openssl-1.1.0.tar.gz \
 && tar xvzf openssl-1.1.0.tar.gz \
 && cd openssl-1.1.0 \
 && ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' \
 && make \
 && make install \
 && ln -s /usr/local/lib/libcrypto.so.1.1 /usr/lib/ \
 && rm /usr/bin/openssl \
 && ln -s /usr/local/ssl/bin/openssl /usr/bin/openssl

# parity 1.9.0
RUN rpm -i http://d1h4xl4cr1h0mo.cloudfront.net/v1.9.0/x86_64-unknown-centos-gnu/parity_1.9.0_x86_64.rpm

# paratii-parity
WORKDIR /paratii-parity
RUN mkdir /paratii-parity/logs
ADD chain.json . 
ADD parity-config.toml .
